### ISSUE TITLE
Telegram webhook

### ISSUE THREAD

**Issue by hostile123** [kamikazechaser/tele-bitcoin-wallet#1]
Please explain more that part
Telegram webhook should point to: https://[yourdomain]/bot

I need to run nodejs telegram api? 

And how and where to put that in config?

**Comment by kamikazechaser** [comment]
To set up the webhook run this in your browser:

```
https://api.telegram.me/bot[your bot token]/setWebhook?url=https://[your domain]/bot
```

To start the bot, run this inside the folder:

```
npm i
node wallet
```

There is nothing else to be added to the config

**Comment by hostile123** [comment]
What's that supossed to do?

I mean where in config i put telegram webhook

**Comment by kamikazechaser** [comment]
There is no need to add it to the config

**Comment by hostile123** [comment]
Ok understand  now

I did it with nbrock when i past it in browser it takes me to telegram api page

Add me for a minute pls

https://t.me/KimJongUng
